workflows:
  ios-native:
    name: iOS Native Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    scripts:
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "AutoSetupApp.xcodeproj" \
            --scheme "AutoSetupApp" \
            --export-options-plist "exportOptions.plist" \
            --archive-directory build/ios/archive \
            --ipa-directory build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
